shared:
  - 'edgecenter/provider.go'
  - 'edgecenter/config.go'
  - 'edgecenter/utils*.go'
  - 'edgecenter/metadata.go'
  - 'edgecenter/provider/**'
  - 'edgecenter/shared/**'
  - 'edgecenter/test/testacc_*.go'
  - 'edgecenter/test/testmain_test.go'
  - 'go.mod'
  - 'go.sum'
  - '.github/workflows/**'
  - '.github/paths-filters.yml'
  - 'Makefile'

cloud:
  - 'edgecenter/services/cloud/**'
  - 'edgecenter/integrationtest/cloud/**'
  - 'edgecenter/integrationtest/support/cloud/**'
  - 'edgecenter/test/helper_test.go'
  - 'edgecenter/test/utils_metadata_test.go'
  - 'edgecenter/test/data_source_edgecenter_availability_zone_test.go'
  - 'edgecenter/test/data_source_edgecenter_flavor_test.go'
  - 'edgecenter/test/data_source_edgecenter_floatingip_test.go'
  - 'edgecenter/test/data_source_edgecenter_image_test.go'
  - 'edgecenter/test/data_source_edgecenter_instance_test.go'
  - 'edgecenter/test/data_source_edgecenter_instanceV2_test.go'
  - 'edgecenter/test/data_source_edgecenter_instance_port_security_test.go'
  - 'edgecenter/test/data_source_edgecenter_lb_l7policy_test.go'
  - 'edgecenter/test/data_source_edgecenter_lb_l7rule_test.go'
  - 'edgecenter/test/data_source_edgecenter_lblistener_test.go'
  - 'edgecenter/test/data_source_edgecenter_lbpool_test.go'
  - 'edgecenter/test/data_source_edgecenter_loadbalancer_test.go'
  - 'edgecenter/test/data_source_edgecenter_network_test.go'
  - 'edgecenter/test/data_source_edgecenter_project_test.go'
  - 'edgecenter/test/data_source_edgecenter_region_test.go'
  - 'edgecenter/test/data_source_edgecenter_reservedfixedip_test.go'
  - 'edgecenter/test/data_source_edgecenter_router_test.go'
  - 'edgecenter/test/data_source_edgecenter_secret_test.go'
  - 'edgecenter/test/data_source_edgecenter_securitygroup_test.go'
  - 'edgecenter/test/data_source_edgecenter_servergroup_test.go'
  - 'edgecenter/test/data_source_edgecenter_snapshot_test.go'
  - 'edgecenter/test/data_source_edgecenter_subnet_test.go'
  - 'edgecenter/test/data_source_edgecenter_useractions_amqp_test.go'
  - 'edgecenter/test/data_source_edgecenter_useractions_log_test.go'
  - 'edgecenter/test/data_source_edgecenter_volume_test.go'
  - 'edgecenter/test/resource_edgecenter_baremetal_test.go'
  - 'edgecenter/test/resource_edgecenter_floatingip_test.go'
  - 'edgecenter/test/resource_edgecenter_instance_test.go'
  - 'edgecenter/test/resource_edgecenter_instanceV2_test.go'
  - 'edgecenter/test/resource_edgecenter_instance_port_security_test.go'
  - 'edgecenter/test/resource_edgecenter_keypair_test.go'
  - 'edgecenter/test/resource_edgecenter_lb_l7policy_test.go'
  - 'edgecenter/test/resource_edgecenter_lb_l7rule_test.go'
  - 'edgecenter/test/resource_edgecenter_lblistener_test.go'
  - 'edgecenter/test/resource_edgecenter_lbmember_test.go'
  - 'edgecenter/test/resource_edgecenter_lbpool_test.go'
  - 'edgecenter/test/resource_edgecenter_lifecyclepolicy_test.go'
  - 'edgecenter/test/resource_edgecenter_loadbalancer_test.go'
  - 'edgecenter/test/resource_edgecenter_network_test.go'
  - 'edgecenter/test/resource_edgecenter_project_test.go'
  - 'edgecenter/test/resource_edgecenter_reservedfixedip_test.go'
  - 'edgecenter/test/resource_edgecenter_router_test.go'
  - 'edgecenter/test/resource_edgecenter_secret_test.go'
  - 'edgecenter/test/resource_edgecenter_securitygroup_test.go'
  - 'edgecenter/test/resource_edgecenter_servergroup_test.go'
  - 'edgecenter/test/resource_edgecenter_snapshot_test.go'
  - 'edgecenter/test/resource_edgecenter_subnet_test.go'
  - 'edgecenter/test/resource_edgecenter_useractions_amqp_test.go'
  - 'edgecenter/test/resource_edgecenter_useractions_log_test.go'
  - 'edgecenter/test/resource_edgecenter_volume_test.go'

mkaas:
  - 'edgecenter/services/mkaas/**'
  - 'edgecenter/services/cloud/network/**'
  - 'edgecenter/integrationtest/mkaas/**'
  - 'edgecenter/integrationtest/support/mkaas/**'
  - 'edgecenter/test/*_mkaas_*'

cdn:
  - 'edgecenter/services/cdn/**'
  - 'edgecenter/integrationtest/cdn/**'
  - 'edgecenter/integrationtest/support/cdn/**'
  - 'edgecenter/test/*_cdn_*'

dns:
  - 'edgecenter/services/dns/**'
  - 'edgecenter/integrationtest/dns/**'
  - 'edgecenter/integrationtest/support/dns/**'
  - 'edgecenter/test/*_dns_*'

storage:
  - 'edgecenter/services/storage/**'
  - 'edgecenter/integrationtest/storage/**'
  - 'edgecenter/integrationtest/support/storage/**'
  - 'edgecenter/test/*_storage_*'

protection:
  - 'edgecenter/services/protection/**'
  - 'edgecenter/integrationtest/protection/**'
  - 'edgecenter/integrationtest/support/protection/**'
  - 'edgecenter/test/*_protection_*'

reseller:
  - 'edgecenter/services/reseller/**'
  - 'edgecenter/services/cloud/network/**'
  - 'edgecenter/integrationtest/reseller/**'
  - 'edgecenter/integrationtest/support/reseller/**'
  - 'edgecenter/test/*_reseller_*'

dbaas:
  - 'edgecenter/services/dbaas/**'
  - 'edgecenter/integrationtest/dbaas/**'
  - 'edgecenter/integrationtest/support/dbaas/**'
  - 'edgecenter/test/*_dbaas_*'
