shared:
  - 'edgecenter/provider.go'
  - 'edgecenter/config.go'
  - 'edgecenter/utils*.go'
  - 'edgecenter/metadata.go'
  - 'edgecenter/test/testacc_*.go'
  - 'edgecenter/test/testmain_test.go'
  - 'go.mod'
  - 'go.sum'
  - '.github/workflows/**'
  - '.github/paths-filters.yml'
  - 'Makefile'

cloud:
  - 'edgecenter/resource_edgecenter_baremetal*'
  - 'edgecenter/resource_edgecenter_floatingip*'
  - 'edgecenter/resource_edgecenter_instance*'
  - 'edgecenter/resource_edgecenter_keypair*'
  - 'edgecenter/resource_edgecenter_lb*'
  - 'edgecenter/resource_edgecenter_lifecyclepolicy*'
  - 'edgecenter/resource_edgecenter_loadbalancer*'
  - 'edgecenter/resource_edgecenter_network*'
  - 'edgecenter/resource_edgecenter_project*'
  - 'edgecenter/resource_edgecenter_reservedfixedip*'
  - 'edgecenter/resource_edgecenter_router*'
  - 'edgecenter/resource_edgecenter_secret*'
  - 'edgecenter/resource_edgecenter_securitygroup*'
  - 'edgecenter/resource_edgecenter_servergroup*'
  - 'edgecenter/resource_edgecenter_snapshot*'
  - 'edgecenter/resource_edgecenter_subnet*'
  - 'edgecenter/resource_edgecenter_volume*'
  - 'edgecenter/data_source_edgecenter_availability_zone*'
  - 'edgecenter/data_source_edgecenter_flavor*'
  - 'edgecenter/data_source_edgecenter_floatingip*'
  - 'edgecenter/data_source_edgecenter_image*'
  - 'edgecenter/data_source_edgecenter_instance*'
  - 'edgecenter/data_source_edgecenter_keypair*'
  - 'edgecenter/data_source_edgecenter_lb*'
  - 'edgecenter/data_source_edgecenter_loadbalancer*'
  - 'edgecenter/data_source_edgecenter_network*'
  - 'edgecenter/data_source_edgecenter_project*'
  - 'edgecenter/data_source_edgecenter_region*'
  - 'edgecenter/data_source_edgecenter_reservedfixedip*'
  - 'edgecenter/data_source_edgecenter_router*'
  - 'edgecenter/data_source_edgecenter_secret*'
  - 'edgecenter/data_source_edgecenter_securitygroup*'
  - 'edgecenter/data_source_edgecenter_servergroup*'
  - 'edgecenter/data_source_edgecenter_shielding_locations*'
  - 'edgecenter/data_source_edgecenter_snapshot*'
  - 'edgecenter/data_source_edgecenter_subnet*'
  - 'edgecenter/data_source_edgecenter_volume*'
  - 'edgecenter/test/*_cloud_*'

mkaas:
  - 'edgecenter/resource_edgecenter_mkaas*'
  - 'edgecenter/resource_edgecenter_k8s*'
  - 'edgecenter/data_source_edgecenter_mkaas*'
  - 'edgecenter/data_source_edgecenter_k8s*'
  - 'edgecenter/test/*_mkaas_*'

cdn:
  - 'edgecenter/resource_edgecenter_cdn*'
  - 'edgecenter/data_source_edgecenter_cdn*'
  - 'edgecenter/test/*_cdn_*'

dns:
  - 'edgecenter/resource_edgecenter_dns*'
  - 'edgecenter/data_source_edgecenter_dns*'
  - 'edgecenter/test/*_dns_*'

storage:
  - 'edgecenter/resource_edgecenter_storage*'
  - 'edgecenter/data_source_edgecenter_storage*'
  - 'edgecenter/test/*_storage_*'

reseller:
  - 'edgecenter/resource_edgecenter_reseller*'
  - 'edgecenter/data_source_edgecenter_reseller*'
  - 'edgecenter/test/*_reseller_*'
