run:
  timeout: 10m
  go: "1.19"

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    - deadcode
    - maligned
    - varcheck
    - nosnakecase
    - interfacer
    - ifshort
    - structcheck
    - golint
    - scopelint
    - exhaustivestruct
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close,io:WriteString
  nakedret:
    max-func-lines: 40
