// Code generated by mockery v2.53.2. DO NOT EDIT.

package cloudmock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// L7PoliciesService is an autogenerated mock type for the L7PoliciesService type
type L7PoliciesService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *L7PoliciesService) Create(_a0 context.Context, _a1 *edgecloud.L7PolicyCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.L7PolicyCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.L7PolicyCreateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.L7PolicyCreateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.L7PolicyCreateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *L7PoliciesService) Delete(_a0 context.Context, _a1 string) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *L7PoliciesService) Get(_a0 context.Context, _a1 string) (*edgecloud.L7Policy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *edgecloud.L7Policy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.L7Policy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.L7Policy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.L7Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: _a0
func (_m *L7PoliciesService) List(_a0 context.Context) ([]edgecloud.L7Policy, *edgecloud.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []edgecloud.L7Policy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]edgecloud.L7Policy, *edgecloud.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []edgecloud.L7Policy); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.L7Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *edgecloud.Response); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *L7PoliciesService) Update(_a0 context.Context, _a1 string, _a2 *edgecloud.L7PolicyUpdateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.L7PolicyUpdateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.L7PolicyUpdateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.L7PolicyUpdateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *edgecloud.L7PolicyUpdateRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewL7PoliciesService creates a new instance of L7PoliciesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewL7PoliciesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *L7PoliciesService {
	mock := &L7PoliciesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
