// Code generated by mockery v2.53.2. DO NOT EDIT.

package cloudmock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// LifeCyclePoliciesService is an autogenerated mock type for the LifeCyclePoliciesService type
type LifeCyclePoliciesService struct {
	mock.Mock
}

// AddSchedules provides a mock function with given fields: _a0, _a1, _a2
func (_m *LifeCyclePoliciesService) AddSchedules(_a0 context.Context, _a1 int, _a2 *edgecloud.LifeCyclePolicyAddSchedulesRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AddSchedules")
	}

	var r0 *edgecloud.LifeCyclePolicy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyAddSchedulesRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyAddSchedulesRequest) *edgecloud.LifeCyclePolicy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *edgecloud.LifeCyclePolicyAddSchedulesRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *edgecloud.LifeCyclePolicyAddSchedulesRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AddVolumes provides a mock function with given fields: _a0, _a1, _a2
func (_m *LifeCyclePoliciesService) AddVolumes(_a0 context.Context, _a1 int, _a2 *edgecloud.LifeCyclePolicyAddVolumesRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AddVolumes")
	}

	var r0 *edgecloud.LifeCyclePolicy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyAddVolumesRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyAddVolumesRequest) *edgecloud.LifeCyclePolicy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *edgecloud.LifeCyclePolicyAddVolumesRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *edgecloud.LifeCyclePolicyAddVolumesRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *LifeCyclePoliciesService) Create(_a0 context.Context, _a1 *edgecloud.LifeCyclePolicyCreateRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *edgecloud.LifeCyclePolicy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.LifeCyclePolicyCreateRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.LifeCyclePolicyCreateRequest) *edgecloud.LifeCyclePolicy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.LifeCyclePolicyCreateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.LifeCyclePolicyCreateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *LifeCyclePoliciesService) Delete(_a0 context.Context, _a1 int) (*edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *edgecloud.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EstimateCronMaxPolicyUsage provides a mock function with given fields: _a0, _a1
func (_m *LifeCyclePoliciesService) EstimateCronMaxPolicyUsage(_a0 context.Context, _a1 *edgecloud.LifeCyclePolicyEstimateCronRequest) (*edgecloud.LifeCyclePolicyMaxPolicyUsage, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EstimateCronMaxPolicyUsage")
	}

	var r0 *edgecloud.LifeCyclePolicyMaxPolicyUsage
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.LifeCyclePolicyEstimateCronRequest) (*edgecloud.LifeCyclePolicyMaxPolicyUsage, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.LifeCyclePolicyEstimateCronRequest) *edgecloud.LifeCyclePolicyMaxPolicyUsage); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicyMaxPolicyUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.LifeCyclePolicyEstimateCronRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.LifeCyclePolicyEstimateCronRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// EstimateIntervalMaxPolicyUsage provides a mock function with given fields: _a0, _a1
func (_m *LifeCyclePoliciesService) EstimateIntervalMaxPolicyUsage(_a0 context.Context, _a1 *edgecloud.LifeCyclePolicyEstimateIntervalRequest) (*edgecloud.LifeCyclePolicyMaxPolicyUsage, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EstimateIntervalMaxPolicyUsage")
	}

	var r0 *edgecloud.LifeCyclePolicyMaxPolicyUsage
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.LifeCyclePolicyEstimateIntervalRequest) (*edgecloud.LifeCyclePolicyMaxPolicyUsage, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.LifeCyclePolicyEstimateIntervalRequest) *edgecloud.LifeCyclePolicyMaxPolicyUsage); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicyMaxPolicyUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.LifeCyclePolicyEstimateIntervalRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.LifeCyclePolicyEstimateIntervalRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: _a0, _a1, _a2
func (_m *LifeCyclePoliciesService) Get(_a0 context.Context, _a1 int, _a2 *edgecloud.LifeCyclePolicyGetOptions) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *edgecloud.LifeCyclePolicy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyGetOptions) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyGetOptions) *edgecloud.LifeCyclePolicy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *edgecloud.LifeCyclePolicyGetOptions) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *edgecloud.LifeCyclePolicyGetOptions) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: _a0, _a1
func (_m *LifeCyclePoliciesService) List(_a0 context.Context, _a1 *edgecloud.LifeCyclePolicyListOptions) ([]edgecloud.LifeCyclePolicy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []edgecloud.LifeCyclePolicy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.LifeCyclePolicyListOptions) ([]edgecloud.LifeCyclePolicy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.LifeCyclePolicyListOptions) []edgecloud.LifeCyclePolicy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.LifeCyclePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.LifeCyclePolicyListOptions) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.LifeCyclePolicyListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RemoveSchedules provides a mock function with given fields: _a0, _a1, _a2
func (_m *LifeCyclePoliciesService) RemoveSchedules(_a0 context.Context, _a1 int, _a2 *edgecloud.LifeCyclePolicyRemoveSchedulesRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSchedules")
	}

	var r0 *edgecloud.LifeCyclePolicy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyRemoveSchedulesRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyRemoveSchedulesRequest) *edgecloud.LifeCyclePolicy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *edgecloud.LifeCyclePolicyRemoveSchedulesRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *edgecloud.LifeCyclePolicyRemoveSchedulesRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RemoveVolumes provides a mock function with given fields: _a0, _a1, _a2
func (_m *LifeCyclePoliciesService) RemoveVolumes(_a0 context.Context, _a1 int, _a2 *edgecloud.LifeCyclePolicyRemoveVolumesRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVolumes")
	}

	var r0 *edgecloud.LifeCyclePolicy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyRemoveVolumesRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyRemoveVolumesRequest) *edgecloud.LifeCyclePolicy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *edgecloud.LifeCyclePolicyRemoveVolumesRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *edgecloud.LifeCyclePolicyRemoveVolumesRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *LifeCyclePoliciesService) Update(_a0 context.Context, _a1 int, _a2 *edgecloud.LifeCyclePolicyUpdateRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *edgecloud.LifeCyclePolicy
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyUpdateRequest) (*edgecloud.LifeCyclePolicy, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.LifeCyclePolicyUpdateRequest) *edgecloud.LifeCyclePolicy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.LifeCyclePolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *edgecloud.LifeCyclePolicyUpdateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *edgecloud.LifeCyclePolicyUpdateRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewLifeCyclePoliciesService creates a new instance of LifeCyclePoliciesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLifeCyclePoliciesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LifeCyclePoliciesService {
	mock := &LifeCyclePoliciesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
