// Code generated by mockery v2.53.2. DO NOT EDIT.

package cloudmock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// ReservedFixedIPsService is an autogenerated mock type for the ReservedFixedIPsService type
type ReservedFixedIPsService struct {
	mock.Mock
}

// AddInstancePorts provides a mock function with given fields: _a0, _a1, _a2
func (_m *ReservedFixedIPsService) AddInstancePorts(_a0 context.Context, _a1 string, _a2 *edgecloud.AddInstancePortsRequest) ([]edgecloud.ReservedFixedIPInstancePort, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AddInstancePorts")
	}

	var r0 []edgecloud.ReservedFixedIPInstancePort
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.AddInstancePortsRequest) ([]edgecloud.ReservedFixedIPInstancePort, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.AddInstancePortsRequest) []edgecloud.ReservedFixedIPInstancePort); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.ReservedFixedIPInstancePort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.AddInstancePortsRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *edgecloud.AddInstancePortsRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *ReservedFixedIPsService) Create(_a0 context.Context, _a1 *edgecloud.ReservedFixedIPCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ReservedFixedIPCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ReservedFixedIPCreateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.ReservedFixedIPCreateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.ReservedFixedIPCreateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *ReservedFixedIPsService) Delete(_a0 context.Context, _a1 string) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *ReservedFixedIPsService) Get(_a0 context.Context, _a1 string) (*edgecloud.ReservedFixedIP, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *edgecloud.ReservedFixedIP
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.ReservedFixedIP, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.ReservedFixedIP); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.ReservedFixedIP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: _a0, _a1
func (_m *ReservedFixedIPsService) List(_a0 context.Context, _a1 *edgecloud.ReservedFixedIPListOptions) ([]edgecloud.ReservedFixedIP, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []edgecloud.ReservedFixedIP
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ReservedFixedIPListOptions) ([]edgecloud.ReservedFixedIP, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ReservedFixedIPListOptions) []edgecloud.ReservedFixedIP); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.ReservedFixedIP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.ReservedFixedIPListOptions) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.ReservedFixedIPListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListInstancePorts provides a mock function with given fields: _a0, _a1
func (_m *ReservedFixedIPsService) ListInstancePorts(_a0 context.Context, _a1 string) ([]edgecloud.ReservedFixedIPInstancePort, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListInstancePorts")
	}

	var r0 []edgecloud.ReservedFixedIPInstancePort
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]edgecloud.ReservedFixedIPInstancePort, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []edgecloud.ReservedFixedIPInstancePort); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.ReservedFixedIPInstancePort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListInstancePortsAvailable provides a mock function with given fields: _a0, _a1
func (_m *ReservedFixedIPsService) ListInstancePortsAvailable(_a0 context.Context, _a1 string) ([]edgecloud.ReservedFixedIPInstancePort, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListInstancePortsAvailable")
	}

	var r0 []edgecloud.ReservedFixedIPInstancePort
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]edgecloud.ReservedFixedIPInstancePort, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []edgecloud.ReservedFixedIPInstancePort); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.ReservedFixedIPInstancePort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ReplaceInstancePorts provides a mock function with given fields: _a0, _a1, _a2
func (_m *ReservedFixedIPsService) ReplaceInstancePorts(_a0 context.Context, _a1 string, _a2 *edgecloud.AddInstancePortsRequest) ([]edgecloud.ReservedFixedIPInstancePort, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceInstancePorts")
	}

	var r0 []edgecloud.ReservedFixedIPInstancePort
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.AddInstancePortsRequest) ([]edgecloud.ReservedFixedIPInstancePort, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.AddInstancePortsRequest) []edgecloud.ReservedFixedIPInstancePort); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.ReservedFixedIPInstancePort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.AddInstancePortsRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *edgecloud.AddInstancePortsRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SwitchVIPStatus provides a mock function with given fields: _a0, _a1, _a2
func (_m *ReservedFixedIPsService) SwitchVIPStatus(_a0 context.Context, _a1 string, _a2 *edgecloud.SwitchVIPStatusRequest) (*edgecloud.ReservedFixedIP, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SwitchVIPStatus")
	}

	var r0 *edgecloud.ReservedFixedIP
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.SwitchVIPStatusRequest) (*edgecloud.ReservedFixedIP, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.SwitchVIPStatusRequest) *edgecloud.ReservedFixedIP); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.ReservedFixedIP)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.SwitchVIPStatusRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *edgecloud.SwitchVIPStatusRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewReservedFixedIPsService creates a new instance of ReservedFixedIPsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservedFixedIPsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservedFixedIPsService {
	mock := &ReservedFixedIPsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
