// Code generated by mockery v2.53.2. DO NOT EDIT.

package cloudmock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// ServerGroupsService is an autogenerated mock type for the ServerGroupsService type
type ServerGroupsService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *ServerGroupsService) Create(_a0 context.Context, _a1 *edgecloud.ServerGroupCreateRequest) (*edgecloud.ServerGroup, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *edgecloud.ServerGroup
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ServerGroupCreateRequest) (*edgecloud.ServerGroup, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ServerGroupCreateRequest) *edgecloud.ServerGroup); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.ServerGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.ServerGroupCreateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.ServerGroupCreateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *ServerGroupsService) Delete(_a0 context.Context, _a1 string) (*edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *ServerGroupsService) Get(_a0 context.Context, _a1 string) (*edgecloud.ServerGroup, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *edgecloud.ServerGroup
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.ServerGroup, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.ServerGroup); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.ServerGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: _a0
func (_m *ServerGroupsService) List(_a0 context.Context) ([]edgecloud.ServerGroup, *edgecloud.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []edgecloud.ServerGroup
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]edgecloud.ServerGroup, *edgecloud.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []edgecloud.ServerGroup); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.ServerGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *edgecloud.Response); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewServerGroupsService creates a new instance of ServerGroupsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerGroupsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerGroupsService {
	mock := &ServerGroupsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
