// Code generated by mockery v2.53.2. DO NOT EDIT.

package cloudmock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// SubnetworksService is an autogenerated mock type for the SubnetworksService type
type SubnetworksService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *SubnetworksService) Create(_a0 context.Context, _a1 *edgecloud.SubnetworkCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.SubnetworkCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.SubnetworkCreateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.SubnetworkCreateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.SubnetworkCreateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *SubnetworksService) Delete(_a0 context.Context, _a1 string) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *SubnetworksService) Get(_a0 context.Context, _a1 string) (*edgecloud.Subnetwork, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *edgecloud.Subnetwork
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.Subnetwork, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.Subnetwork); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Subnetwork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: _a0, _a1
func (_m *SubnetworksService) List(_a0 context.Context, _a1 *edgecloud.SubnetworkListOptions) ([]edgecloud.Subnetwork, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []edgecloud.Subnetwork
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.SubnetworkListOptions) ([]edgecloud.Subnetwork, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.SubnetworkListOptions) []edgecloud.Subnetwork); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.Subnetwork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.SubnetworkListOptions) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.SubnetworkListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MetadataCreate provides a mock function with given fields: _a0, _a1, _a2
func (_m *SubnetworksService) MetadataCreate(_a0 context.Context, _a1 string, _a2 *edgecloud.Metadata) (*edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MetadataCreate")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.Metadata) (*edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.Metadata) *edgecloud.Response); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.Metadata) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetadataDeleteItem provides a mock function with given fields: _a0, _a1, _a2
func (_m *SubnetworksService) MetadataDeleteItem(_a0 context.Context, _a1 string, _a2 *edgecloud.MetadataItemOptions) (*edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MetadataDeleteItem")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.MetadataItemOptions) (*edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.MetadataItemOptions) *edgecloud.Response); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.MetadataItemOptions) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetadataGetItem provides a mock function with given fields: _a0, _a1, _a2
func (_m *SubnetworksService) MetadataGetItem(_a0 context.Context, _a1 string, _a2 *edgecloud.MetadataItemOptions) (*edgecloud.MetadataDetailed, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MetadataGetItem")
	}

	var r0 *edgecloud.MetadataDetailed
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.MetadataItemOptions) (*edgecloud.MetadataDetailed, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.MetadataItemOptions) *edgecloud.MetadataDetailed); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.MetadataDetailed)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.MetadataItemOptions) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *edgecloud.MetadataItemOptions) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MetadataList provides a mock function with given fields: _a0, _a1
func (_m *SubnetworksService) MetadataList(_a0 context.Context, _a1 string) ([]edgecloud.MetadataDetailed, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MetadataList")
	}

	var r0 []edgecloud.MetadataDetailed
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]edgecloud.MetadataDetailed, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []edgecloud.MetadataDetailed); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.MetadataDetailed)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MetadataUpdate provides a mock function with given fields: _a0, _a1, _a2
func (_m *SubnetworksService) MetadataUpdate(_a0 context.Context, _a1 string, _a2 *edgecloud.Metadata) (*edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MetadataUpdate")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.Metadata) (*edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.Metadata) *edgecloud.Response); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.Metadata) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *SubnetworksService) Update(_a0 context.Context, _a1 string, _a2 *edgecloud.SubnetworkUpdateRequest) (*edgecloud.Subnetwork, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *edgecloud.Subnetwork
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.SubnetworkUpdateRequest) (*edgecloud.Subnetwork, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.SubnetworkUpdateRequest) *edgecloud.Subnetwork); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Subnetwork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.SubnetworkUpdateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *edgecloud.SubnetworkUpdateRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewSubnetworksService creates a new instance of SubnetworksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubnetworksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubnetworksService {
	mock := &SubnetworksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
