// Code generated by mockery v2.53.2. DO NOT EDIT.

package cloudmock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// TasksService is an autogenerated mock type for the TasksService type
type TasksService struct {
	mock.Mock
}

// Acknowledge provides a mock function with given fields: _a0, _a1
func (_m *TasksService) Acknowledge(_a0 context.Context, _a1 string) (*edgecloud.Task, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Acknowledge")
	}

	var r0 *edgecloud.Task
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.Task, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.Task); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AcknowledgeAll provides a mock function with given fields: _a0, _a1
func (_m *TasksService) AcknowledgeAll(_a0 context.Context, _a1 *edgecloud.TaskAcknowledgeAllOptions) (*edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeAll")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.TaskAcknowledgeAllOptions) (*edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.TaskAcknowledgeAllOptions) *edgecloud.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.TaskAcknowledgeAllOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *TasksService) Get(_a0 context.Context, _a1 string) (*edgecloud.Task, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *edgecloud.Task
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.Task, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.Task); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: _a0, _a1
func (_m *TasksService) List(_a0 context.Context, _a1 *edgecloud.TaskListOptions) ([]edgecloud.Task, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []edgecloud.Task
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.TaskListOptions) ([]edgecloud.Task, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.TaskListOptions) []edgecloud.Task); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.TaskListOptions) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.TaskListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListActive provides a mock function with given fields: _a0
func (_m *TasksService) ListActive(_a0 context.Context) ([]edgecloud.Task, *edgecloud.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []edgecloud.Task
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]edgecloud.Task, *edgecloud.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []edgecloud.Task); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *edgecloud.Response); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewTasksService creates a new instance of TasksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTasksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TasksService {
	mock := &TasksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
