// Code generated by mockery v2.53.2. DO NOT EDIT.

package mkaasmock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// MKaaSService is an autogenerated mock type for the MKaaSService type
type MKaaSService struct {
	mock.Mock
}

// ClusterCreate provides a mock function with given fields: _a0, _a1
func (_m *MKaaSService) ClusterCreate(_a0 context.Context, _a1 edgecloud.MKaaSClusterCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClusterCreate")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, edgecloud.MKaaSClusterCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, edgecloud.MKaaSClusterCreateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, edgecloud.MKaaSClusterCreateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, edgecloud.MKaaSClusterCreateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterDelete provides a mock function with given fields: _a0, _a1
func (_m *MKaaSService) ClusterDelete(_a0 context.Context, _a1 int) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClusterDelete")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterGet provides a mock function with given fields: _a0, _a1
func (_m *MKaaSService) ClusterGet(_a0 context.Context, _a1 int) (*edgecloud.MKaaSCluster, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClusterGet")
	}

	var r0 *edgecloud.MKaaSCluster
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*edgecloud.MKaaSCluster, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *edgecloud.MKaaSCluster); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.MKaaSCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterUpdateMasterNodeCount provides a mock function with given fields: ctx, clusterID, reqBody
func (_m *MKaaSService) ClusterUpdateMasterNodeCount(ctx context.Context, clusterID int, reqBody edgecloud.MKaaSClusterUpdateMasterNodeCountRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for ClusterUpdateMasterNodeCount")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, edgecloud.MKaaSClusterUpdateMasterNodeCountRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, edgecloud.MKaaSClusterUpdateMasterNodeCountRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, edgecloud.MKaaSClusterUpdateMasterNodeCountRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, edgecloud.MKaaSClusterUpdateMasterNodeCountRequest) error); ok {
		r2 = rf(ctx, clusterID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterUpdateName provides a mock function with given fields: ctx, clusterID, reqBody
func (_m *MKaaSService) ClusterUpdateName(ctx context.Context, clusterID int, reqBody edgecloud.MKaaSClusterUpdateNameRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for ClusterUpdateName")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, edgecloud.MKaaSClusterUpdateNameRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, edgecloud.MKaaSClusterUpdateNameRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, edgecloud.MKaaSClusterUpdateNameRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, edgecloud.MKaaSClusterUpdateNameRequest) error); ok {
		r2 = rf(ctx, clusterID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterUpgradeVersion provides a mock function with given fields: ctx, clusterID, reqBody
func (_m *MKaaSService) ClusterUpgradeVersion(ctx context.Context, clusterID int, reqBody edgecloud.MKaaSClusterUpgradeVersionRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for ClusterUpgradeVersion")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, edgecloud.MKaaSClusterUpgradeVersionRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, edgecloud.MKaaSClusterUpgradeVersionRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, edgecloud.MKaaSClusterUpgradeVersionRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, edgecloud.MKaaSClusterUpgradeVersionRequest) error); ok {
		r2 = rf(ctx, clusterID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClustersList provides a mock function with given fields: _a0, _a1
func (_m *MKaaSService) ClustersList(_a0 context.Context, _a1 *edgecloud.MKaaSClusterListOptions) ([]edgecloud.MKaaSCluster, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClustersList")
	}

	var r0 []edgecloud.MKaaSCluster
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.MKaaSClusterListOptions) ([]edgecloud.MKaaSCluster, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.MKaaSClusterListOptions) []edgecloud.MKaaSCluster); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.MKaaSCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.MKaaSClusterListOptions) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.MKaaSClusterListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FlavorsList provides a mock function with given fields: ctx, opts
func (_m *MKaaSService) FlavorsList(ctx context.Context, opts *edgecloud.MKaaSFlavorListOptions) (*edgecloud.MKaaSFlavorsList, *edgecloud.Response, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for FlavorsList")
	}

	var r0 *edgecloud.MKaaSFlavorsList
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.MKaaSFlavorListOptions) (*edgecloud.MKaaSFlavorsList, *edgecloud.Response, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.MKaaSFlavorListOptions) *edgecloud.MKaaSFlavorsList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.MKaaSFlavorsList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.MKaaSFlavorListOptions) *edgecloud.Response); ok {
		r1 = rf(ctx, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.MKaaSFlavorListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NodesDelete provides a mock function with given fields: ctx, clusterID, poolID, reqBody
func (_m *MKaaSService) NodesDelete(ctx context.Context, clusterID int, poolID int, reqBody edgecloud.MKaaSNodesDeleteRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for NodesDelete")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSNodesDeleteRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSNodesDeleteRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, edgecloud.MKaaSNodesDeleteRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, edgecloud.MKaaSNodesDeleteRequest) error); ok {
		r2 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NodesList provides a mock function with given fields: ctx, clusterID, poolID, opts
func (_m *MKaaSService) NodesList(ctx context.Context, clusterID int, poolID int, opts *edgecloud.MKaaSNodeListOptions) ([]edgecloud.MKaaSNode, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID, opts)

	if len(ret) == 0 {
		panic("no return value specified for NodesList")
	}

	var r0 []edgecloud.MKaaSNode
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *edgecloud.MKaaSNodeListOptions) ([]edgecloud.MKaaSNode, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *edgecloud.MKaaSNodeListOptions) []edgecloud.MKaaSNode); ok {
		r0 = rf(ctx, clusterID, poolID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.MKaaSNode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *edgecloud.MKaaSNodeListOptions) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, *edgecloud.MKaaSNodeListOptions) error); ok {
		r2 = rf(ctx, clusterID, poolID, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolCreate provides a mock function with given fields: ctx, clusterID, reqBody
func (_m *MKaaSService) PoolCreate(ctx context.Context, clusterID int, reqBody edgecloud.MKaaSPoolCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for PoolCreate")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, edgecloud.MKaaSPoolCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, edgecloud.MKaaSPoolCreateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, edgecloud.MKaaSPoolCreateRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, edgecloud.MKaaSPoolCreateRequest) error); ok {
		r2 = rf(ctx, clusterID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolDelete provides a mock function with given fields: ctx, clusterID, poolID
func (_m *MKaaSService) PoolDelete(ctx context.Context, clusterID int, poolID int) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID)

	if len(ret) == 0 {
		panic("no return value specified for PoolDelete")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, poolID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, clusterID, poolID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolGet provides a mock function with given fields: ctx, clusterID, poolID
func (_m *MKaaSService) PoolGet(ctx context.Context, clusterID int, poolID int) (*edgecloud.MKaaSPool, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID)

	if len(ret) == 0 {
		panic("no return value specified for PoolGet")
	}

	var r0 *edgecloud.MKaaSPool
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*edgecloud.MKaaSPool, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *edgecloud.MKaaSPool); ok {
		r0 = rf(ctx, clusterID, poolID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.MKaaSPool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, clusterID, poolID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolUpdateAutoscaling provides a mock function with given fields: ctx, clusterID, poolID, reqBody
func (_m *MKaaSService) PoolUpdateAutoscaling(ctx context.Context, clusterID int, poolID int, reqBody edgecloud.MKaaSPoolUpdateAutoscalingRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for PoolUpdateAutoscaling")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateAutoscalingRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateAutoscalingRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateAutoscalingRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateAutoscalingRequest) error); ok {
		r2 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolUpdateLabels provides a mock function with given fields: ctx, clusterID, poolID, reqBody
func (_m *MKaaSService) PoolUpdateLabels(ctx context.Context, clusterID int, poolID int, reqBody edgecloud.MKaaSPoolUpdateLabelsRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for PoolUpdateLabels")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateLabelsRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateLabelsRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateLabelsRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateLabelsRequest) error); ok {
		r2 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolUpdateName provides a mock function with given fields: ctx, clusterID, poolID, reqBody
func (_m *MKaaSService) PoolUpdateName(ctx context.Context, clusterID int, poolID int, reqBody edgecloud.MKaaSPoolUpdateNameRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for PoolUpdateName")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateNameRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateNameRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateNameRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateNameRequest) error); ok {
		r2 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolUpdateNodeCount provides a mock function with given fields: ctx, clusterID, poolID, reqBody
func (_m *MKaaSService) PoolUpdateNodeCount(ctx context.Context, clusterID int, poolID int, reqBody edgecloud.MKaaSPoolUpdateScaleRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for PoolUpdateNodeCount")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateScaleRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateScaleRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateScaleRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateScaleRequest) error); ok {
		r2 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolUpdateSecurityGroups provides a mock function with given fields: ctx, clusterID, poolID, reqBody
func (_m *MKaaSService) PoolUpdateSecurityGroups(ctx context.Context, clusterID int, poolID int, reqBody edgecloud.MKaaSPoolUpdateSecurityGroupsRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for PoolUpdateSecurityGroups")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateSecurityGroupsRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateSecurityGroupsRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateSecurityGroupsRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateSecurityGroupsRequest) error); ok {
		r2 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolUpdateTaints provides a mock function with given fields: ctx, clusterID, poolID, reqBody
func (_m *MKaaSService) PoolUpdateTaints(ctx context.Context, clusterID int, poolID int, reqBody edgecloud.MKaaSPoolUpdateTaintsRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, poolID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for PoolUpdateTaints")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateTaintsRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, poolID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateTaintsRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateTaintsRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, edgecloud.MKaaSPoolUpdateTaintsRequest) error); ok {
		r2 = rf(ctx, clusterID, poolID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PoolsList provides a mock function with given fields: ctx, clusterID, opts
func (_m *MKaaSService) PoolsList(ctx context.Context, clusterID int, opts *edgecloud.MKaaSPoolListOptions) ([]edgecloud.MKaaSPool, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, opts)

	if len(ret) == 0 {
		panic("no return value specified for PoolsList")
	}

	var r0 []edgecloud.MKaaSPool
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.MKaaSPoolListOptions) ([]edgecloud.MKaaSPool, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *edgecloud.MKaaSPoolListOptions) []edgecloud.MKaaSPool); ok {
		r0 = rf(ctx, clusterID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.MKaaSPool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *edgecloud.MKaaSPoolListOptions) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *edgecloud.MKaaSPoolListOptions) error); ok {
		r2 = rf(ctx, clusterID, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// VersionsList provides a mock function with given fields: ctx, regionID
func (_m *MKaaSService) VersionsList(ctx context.Context, regionID int) (*edgecloud.MKaaSKubernetesVersionsResult, *edgecloud.Response, error) {
	ret := _m.Called(ctx, regionID)

	if len(ret) == 0 {
		panic("no return value specified for VersionsList")
	}

	var r0 *edgecloud.MKaaSKubernetesVersionsResult
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*edgecloud.MKaaSKubernetesVersionsResult, *edgecloud.Response, error)); ok {
		return rf(ctx, regionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *edgecloud.MKaaSKubernetesVersionsResult); ok {
		r0 = rf(ctx, regionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.MKaaSKubernetesVersionsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) *edgecloud.Response); ok {
		r1 = rf(ctx, regionID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, regionID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMKaaSService creates a new instance of MKaaSService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMKaaSService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MKaaSService {
	mock := &MKaaSService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
