// Code generated by mockery v2.53.2. DO NOT EDIT.

package dnsmock

import (
	context "context"

	dnssdk "github.com/Edge-Center/edgecenter-dns-sdk-go"

	mock "github.com/stretchr/testify/mock"
)

// DNSClientService is an autogenerated mock type for the DNSClientService type
type DNSClientService struct {
	mock.Mock
}

// CreateRRSet provides a mock function with given fields: ctx, zone, name, recordType, record
func (_m *DNSClientService) CreateRRSet(ctx context.Context, zone string, name string, recordType string, record dnssdk.RRSet) error {
	ret := _m.Called(ctx, zone, name, recordType, record)

	if len(ret) == 0 {
		panic("no return value specified for CreateRRSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, dnssdk.RRSet) error); ok {
		r0 = rf(ctx, zone, name, recordType, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSecondaryZone provides a mock function with given fields: ctx, req
func (_m *DNSClientService) CreateSecondaryZone(ctx context.Context, req dnssdk.CreateSecondaryZoneRequest) (dnssdk.SecondaryZone, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecondaryZone")
	}

	var r0 dnssdk.SecondaryZone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dnssdk.CreateSecondaryZoneRequest) (dnssdk.SecondaryZone, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dnssdk.CreateSecondaryZoneRequest) dnssdk.SecondaryZone); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(dnssdk.SecondaryZone)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dnssdk.CreateSecondaryZoneRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateZone provides a mock function with given fields: ctx, name
func (_m *DNSClientService) CreateZone(ctx context.Context, name string) (uint64, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateZone")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRRSet provides a mock function with given fields: ctx, zone, name, recordType
func (_m *DNSClientService) DeleteRRSet(ctx context.Context, zone string, name string, recordType string) error {
	ret := _m.Called(ctx, zone, name, recordType)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRRSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, zone, name, recordType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSecondaryZone provides a mock function with given fields: ctx, name
func (_m *DNSClientService) DeleteSecondaryZone(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecondaryZone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteZone provides a mock function with given fields: ctx, name
func (_m *DNSClientService) DeleteZone(ctx context.Context, name string) error {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteZone")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSecondaryZone provides a mock function with given fields: ctx, name
func (_m *DNSClientService) GetSecondaryZone(ctx context.Context, name string) (dnssdk.SecondaryZone, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSecondaryZone")
	}

	var r0 dnssdk.SecondaryZone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dnssdk.SecondaryZone, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dnssdk.SecondaryZone); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(dnssdk.SecondaryZone)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RRSet provides a mock function with given fields: ctx, zone, name, recordType
func (_m *DNSClientService) RRSet(ctx context.Context, zone string, name string, recordType string) (dnssdk.RRSet, error) {
	ret := _m.Called(ctx, zone, name, recordType)

	if len(ret) == 0 {
		panic("no return value specified for RRSet")
	}

	var r0 dnssdk.RRSet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (dnssdk.RRSet, error)); ok {
		return rf(ctx, zone, name, recordType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) dnssdk.RRSet); ok {
		r0 = rf(ctx, zone, name, recordType)
	} else {
		r0 = ret.Get(0).(dnssdk.RRSet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, zone, name, recordType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecondaryZones provides a mock function with given fields: ctx
func (_m *DNSClientService) SecondaryZones(ctx context.Context) ([]dnssdk.SecondaryZone, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SecondaryZones")
	}

	var r0 []dnssdk.SecondaryZone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dnssdk.SecondaryZone, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dnssdk.SecondaryZone); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dnssdk.SecondaryZone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRRSet provides a mock function with given fields: ctx, zone, name, recordType, record
func (_m *DNSClientService) UpdateRRSet(ctx context.Context, zone string, name string, recordType string, record dnssdk.RRSet) error {
	ret := _m.Called(ctx, zone, name, recordType, record)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRRSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, dnssdk.RRSet) error); ok {
		r0 = rf(ctx, zone, name, recordType, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSecondaryZone provides a mock function with given fields: ctx, name, req
func (_m *DNSClientService) UpdateSecondaryZone(ctx context.Context, name string, req dnssdk.UpdateSecondaryZoneRequest) (dnssdk.SecondaryZone, error) {
	ret := _m.Called(ctx, name, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecondaryZone")
	}

	var r0 dnssdk.SecondaryZone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dnssdk.UpdateSecondaryZoneRequest) (dnssdk.SecondaryZone, error)); ok {
		return rf(ctx, name, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dnssdk.UpdateSecondaryZoneRequest) dnssdk.SecondaryZone); ok {
		r0 = rf(ctx, name, req)
	} else {
		r0 = ret.Get(0).(dnssdk.SecondaryZone)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dnssdk.UpdateSecondaryZoneRequest) error); ok {
		r1 = rf(ctx, name, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Zone provides a mock function with given fields: ctx, name
func (_m *DNSClientService) Zone(ctx context.Context, name string) (dnssdk.Zone, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Zone")
	}

	var r0 dnssdk.Zone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dnssdk.Zone, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dnssdk.Zone); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(dnssdk.Zone)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDNSClientService creates a new instance of DNSClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDNSClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DNSClientService {
	mock := &DNSClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
