# Generated by v2migrate (terraform-provider-edgecenter).
# Review the blocks, then run:
#   terraform plan -out=v2-migrate.tfplan
#   terraform apply v2-migrate.tfplan
# The plan must only import and forget resources, no destroy and no create.
# After a successful apply delete this file, terraform plan must then show no changes.
# Requires terraform >= 1.7.

removed {
  from = edgecenter_loadbalancer.farm
  lifecycle {
    destroy = false
  }
}

import {
  to = edgecenter_loadbalancerv2.farm["a"]
  id = "1:2:aaaa1111-0000-0000-0000-000000000000"
}

import {
  to = edgecenter_loadbalancerv2.farm["b"]
  id = "1:2:bbbb2222-0000-0000-0000-000000000000"
}

removed {
  from = edgecenter_instance.workers
  lifecycle {
    destroy = false
  }
}

import {
  to = edgecenter_instanceV2.workers[0]
  id = "1:2:11111111-2222-3333-4444-555555555555"
}

import {
  to = edgecenter_instanceV2.workers[1]
  id = "1:2:66666666-7777-8888-9999-000000000000"
}

removed {
  from = edgecenter_instance.min
  lifecycle {
    destroy = false
  }
}

import {
  to = edgecenter_instanceV2.min
  id = "<project_id>:<region_id>:<id>" # TODO(v2migrate): fill the import id
}
