# Generated by v2migrate (terraform-provider-edgecenter).
# Review the blocks, then run:
#   terraform plan -out=v2-migrate.tfplan
#   terraform apply v2-migrate.tfplan
# The plan must only import and forget resources, no destroy and no create.
# After a successful apply delete this file, terraform plan must then show no changes.
# Requires terraform >= 1.7.

removed {
  from = edgecenter_instance.solo
  lifecycle {
    destroy = false
  }
}

import {
  to = edgecenter_instanceV2.solo
  id = "<project_id>:<region_id>:<id>" # TODO(v2migrate): fill the import id
}
