package converter

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

type migrationEntry struct {
	conv    *blockConv
	state   *stateResource
	rules   *Rules
	extract *extraction
}

func renderIndexKey(key any) string {
	switch v := key.(type) {
	case nil:
		return ""
	case string:
		return "[" + strconv.Quote(v) + "]"
	case json.Number:
		return "[" + v.String() + "]"
	}

	return ""
}

func buildMigrations(entries []migrationEntry, rep *Report) string {
	var b strings.Builder
	b.WriteString("# Generated by v2migrate (terraform-provider-edgecenter).\n")
	b.WriteString("# Review the blocks, then run:\n")
	b.WriteString("#   terraform plan -out=v2-migrate.tfplan\n")
	b.WriteString("#   terraform apply v2-migrate.tfplan\n")
	b.WriteString("# The plan must only import and forget resources, no destroy and no create.\n")
	b.WriteString("# After a successful apply delete this file, terraform plan must then show no changes.\n")
	b.WriteString("# Requires terraform >= 1.7.\n")

	for _, e := range entries {
		if e.extract != nil {
			writeExtractImport(&b, e, rep)
			continue
		}
		writeResourceMigration(&b, e, rep)
	}

	return b.String()
}

func writeResourceMigration(b *strings.Builder, e migrationEntry, rep *Report) {
	c := e.conv
	fmt.Fprintf(b, "\nremoved {\n  from = %s\n  lifecycle {\n    destroy = false\n  }\n}\n", c.oldAddr)
	rep.RemovedN++

	if e.state == nil || len(e.state.Instances) == 0 {
		id, _ := expandImportID(e.rules.ImportID, nil)
		writeImport(b, c.newAddr, id, true, rep)
		rep.warn(c.f.path, c.block.TypeRange.Start.Line, c.oldAddr, "no state entry found, the import id in "+rep.Migrations+" is a placeholder, fill it manually")
		return
	}
	for _, inst := range e.state.Instances {
		id, missing := expandImportID(e.rules.ImportID, inst.Attributes)
		writeImport(b, c.newAddr+renderIndexKey(inst.IndexKey), id, len(missing) > 0, rep)
		if len(missing) > 0 {
			rep.warn(c.f.path, c.block.TypeRange.Start.Line, c.oldAddr, "state attributes "+strings.Join(missing, ", ")+" are empty, fill the import id manually")
		}
	}
}

func writeExtractImport(b *strings.Builder, e migrationEntry, rep *Report) {
	ex := e.extract
	newAddr := ex.newType + "." + ex.newName
	var attrs map[string]any
	if e.state != nil && len(e.state.Instances) == 1 {
		attrs = e.state.Instances[0].Attributes
	}
	id, missing := expandImportID(ex.importTmpl, attrs)
	writeImport(b, newAddr, id, len(missing) > 0 || attrs == nil, rep)
	if len(missing) > 0 || attrs == nil {
		rep.warn(ex.file, 0, ex.parentType+"."+ex.parentName, "could not resolve the import id for the extracted "+newAddr+", fill it manually")
	}
}

func writeImport(b *strings.Builder, to, id string, placeholder bool, rep *Report) {
	fmt.Fprintf(b, "\nimport {\n  to = %s\n  id = %q", to, id)
	if placeholder {
		b.WriteString(" # TODO(v2migrate): fill the import id")
		rep.Placeholder = true
	}
	b.WriteString("\n}\n")
	rep.ImportsN++
}
