// Code generated by mockery v2.53.2. DO NOT EDIT.

package resellermock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// ResellerNetworksService is an autogenerated mock type for the ResellerNetworksService type
type ResellerNetworksService struct {
	mock.Mock
}

// List provides a mock function with given fields: _a0, _a1
func (_m *ResellerNetworksService) List(_a0 context.Context, _a1 *edgecloud.ResellerNetworksListRequest) (*edgecloud.ResellerNetworks, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *edgecloud.ResellerNetworks
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ResellerNetworksListRequest) (*edgecloud.ResellerNetworks, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ResellerNetworksListRequest) *edgecloud.ResellerNetworks); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.ResellerNetworks)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.ResellerNetworksListRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.ResellerNetworksListRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewResellerNetworksService creates a new instance of ResellerNetworksService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResellerNetworksService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResellerNetworksService {
	mock := &ResellerNetworksService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
