// Code generated by mockery v2.53.2. DO NOT EDIT.

package resellermock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// ResellerImageV2Service is an autogenerated mock type for the ResellerImageV2Service type
type ResellerImageV2Service struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *ResellerImageV2Service) Delete(_a0 context.Context, _a1 string, _a2 int, _a3 *edgecloud.ResellerImageV2DeleteOptions) (*edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, *edgecloud.ResellerImageV2DeleteOptions) (*edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, *edgecloud.ResellerImageV2DeleteOptions) *edgecloud.Response); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, *edgecloud.ResellerImageV2DeleteOptions) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1, _a2
func (_m *ResellerImageV2Service) List(_a0 context.Context, _a1 string, _a2 int) (*edgecloud.ResellerImageV2List, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *edgecloud.ResellerImageV2List
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*edgecloud.ResellerImageV2List, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *edgecloud.ResellerImageV2List); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.ResellerImageV2List)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListByRole provides a mock function with given fields: _a0
func (_m *ResellerImageV2Service) ListByRole(_a0 context.Context) (*edgecloud.ResellerImageV2List, *edgecloud.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListByRole")
	}

	var r0 *edgecloud.ResellerImageV2List
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (*edgecloud.ResellerImageV2List, *edgecloud.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *edgecloud.ResellerImageV2List); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.ResellerImageV2List)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *edgecloud.Response); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *ResellerImageV2Service) Update(_a0 context.Context, _a1 *edgecloud.ResellerImageV2UpdateRequest) (*edgecloud.ResellerImageV2, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *edgecloud.ResellerImageV2
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ResellerImageV2UpdateRequest) (*edgecloud.ResellerImageV2, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.ResellerImageV2UpdateRequest) *edgecloud.ResellerImageV2); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.ResellerImageV2)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.ResellerImageV2UpdateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.ResellerImageV2UpdateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewResellerImageV2Service creates a new instance of ResellerImageV2Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResellerImageV2Service(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResellerImageV2Service {
	mock := &ResellerImageV2Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
