// Code generated by mockery v2.53.2. DO NOT EDIT.

package dbaasmock

import (
	context "context"

	edgecloud "github.com/Edge-Center/edgecentercloud-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// DBaaSService is an autogenerated mock type for the DBaaSService type
type DBaaSService struct {
	mock.Mock
}

// BackupCreate provides a mock function with given fields: ctx, reqBody
func (_m *DBaaSService) BackupCreate(ctx context.Context, reqBody edgecloud.DBaaSBackupCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for BackupCreate")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, edgecloud.DBaaSBackupCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, edgecloud.DBaaSBackupCreateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, edgecloud.DBaaSBackupCreateRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, edgecloud.DBaaSBackupCreateRequest) error); ok {
		r2 = rf(ctx, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BackupDelete provides a mock function with given fields: ctx, backupID
func (_m *DBaaSService) BackupDelete(ctx context.Context, backupID string) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(ctx, backupID)

	if len(ret) == 0 {
		panic("no return value specified for BackupDelete")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(ctx, backupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.TaskResponse); ok {
		r0 = rf(ctx, backupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(ctx, backupID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, backupID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BackupGet provides a mock function with given fields: ctx, backupID, includePrices
func (_m *DBaaSService) BackupGet(ctx context.Context, backupID string, includePrices bool) (*edgecloud.DBaaSBackup, *edgecloud.Response, error) {
	ret := _m.Called(ctx, backupID, includePrices)

	if len(ret) == 0 {
		panic("no return value specified for BackupGet")
	}

	var r0 *edgecloud.DBaaSBackup
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*edgecloud.DBaaSBackup, *edgecloud.Response, error)); ok {
		return rf(ctx, backupID, includePrices)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *edgecloud.DBaaSBackup); ok {
		r0 = rf(ctx, backupID, includePrices)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.DBaaSBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) *edgecloud.Response); ok {
		r1 = rf(ctx, backupID, includePrices)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, bool) error); ok {
		r2 = rf(ctx, backupID, includePrices)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BackupUpdate provides a mock function with given fields: ctx, backupID, reqBody
func (_m *DBaaSService) BackupUpdate(ctx context.Context, backupID string, reqBody edgecloud.DBaaSBackupUpdateRequest) (*edgecloud.DBaaSBackup, *edgecloud.Response, error) {
	ret := _m.Called(ctx, backupID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for BackupUpdate")
	}

	var r0 *edgecloud.DBaaSBackup
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSBackupUpdateRequest) (*edgecloud.DBaaSBackup, *edgecloud.Response, error)); ok {
		return rf(ctx, backupID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSBackupUpdateRequest) *edgecloud.DBaaSBackup); ok {
		r0 = rf(ctx, backupID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.DBaaSBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, edgecloud.DBaaSBackupUpdateRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, backupID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, edgecloud.DBaaSBackupUpdateRequest) error); ok {
		r2 = rf(ctx, backupID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BackupsList provides a mock function with given fields: ctx, opts
func (_m *DBaaSService) BackupsList(ctx context.Context, opts *edgecloud.DBaaSBackupListOptions) ([]edgecloud.DBaaSBackup, *edgecloud.Response, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BackupsList")
	}

	var r0 []edgecloud.DBaaSBackup
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.DBaaSBackupListOptions) ([]edgecloud.DBaaSBackup, *edgecloud.Response, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.DBaaSBackupListOptions) []edgecloud.DBaaSBackup); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.DBaaSBackup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.DBaaSBackupListOptions) *edgecloud.Response); ok {
		r1 = rf(ctx, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.DBaaSBackupListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BackupsListPage provides a mock function with given fields: ctx, opts
func (_m *DBaaSService) BackupsListPage(ctx context.Context, opts *edgecloud.DBaaSBackupListOptions) (*edgecloud.DBaaSBackupsPage, *edgecloud.Response, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BackupsListPage")
	}

	var r0 *edgecloud.DBaaSBackupsPage
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.DBaaSBackupListOptions) (*edgecloud.DBaaSBackupsPage, *edgecloud.Response, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.DBaaSBackupListOptions) *edgecloud.DBaaSBackupsPage); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.DBaaSBackupsPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.DBaaSBackupListOptions) *edgecloud.Response); ok {
		r1 = rf(ctx, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.DBaaSBackupListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterCreate provides a mock function with given fields: _a0, _a1
func (_m *DBaaSService) ClusterCreate(_a0 context.Context, _a1 edgecloud.DBaaSClusterCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClusterCreate")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, edgecloud.DBaaSClusterCreateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, edgecloud.DBaaSClusterCreateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, edgecloud.DBaaSClusterCreateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, edgecloud.DBaaSClusterCreateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterDelete provides a mock function with given fields: _a0, _a1
func (_m *DBaaSService) ClusterDelete(_a0 context.Context, _a1 string) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClusterDelete")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterGet provides a mock function with given fields: _a0, _a1
func (_m *DBaaSService) ClusterGet(_a0 context.Context, _a1 string) (*edgecloud.DBaaSCluster, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClusterGet")
	}

	var r0 *edgecloud.DBaaSCluster
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*edgecloud.DBaaSCluster, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *edgecloud.DBaaSCluster); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.DBaaSCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterUpdate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DBaaSService) ClusterUpdate(_a0 context.Context, _a1 string, _a2 edgecloud.DBaaSClusterUpdateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ClusterUpdate")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSClusterUpdateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSClusterUpdateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, edgecloud.DBaaSClusterUpdateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, edgecloud.DBaaSClusterUpdateRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClusterUpdateAccessControl provides a mock function with given fields: _a0, _a1, _a2
func (_m *DBaaSService) ClusterUpdateAccessControl(_a0 context.Context, _a1 string, _a2 edgecloud.DBaaSClusterAccessControlUpdateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ClusterUpdateAccessControl")
	}

	var r0 *edgecloud.TaskResponse
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSClusterAccessControlUpdateRequest) (*edgecloud.TaskResponse, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSClusterAccessControlUpdateRequest) *edgecloud.TaskResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, edgecloud.DBaaSClusterAccessControlUpdateRequest) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, edgecloud.DBaaSClusterAccessControlUpdateRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ClustersList provides a mock function with given fields: _a0, _a1
func (_m *DBaaSService) ClustersList(_a0 context.Context, _a1 *edgecloud.DBaaSClusterListOptions) ([]edgecloud.DBaaSCluster, *edgecloud.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClustersList")
	}

	var r0 []edgecloud.DBaaSCluster
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.DBaaSClusterListOptions) ([]edgecloud.DBaaSCluster, *edgecloud.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.DBaaSClusterListOptions) []edgecloud.DBaaSCluster); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.DBaaSCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.DBaaSClusterListOptions) *edgecloud.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.DBaaSClusterListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DatabaseCreate provides a mock function with given fields: ctx, clusterID, reqBody
func (_m *DBaaSService) DatabaseCreate(ctx context.Context, clusterID string, reqBody edgecloud.DBaaSDatabaseCreateRequest) (*edgecloud.DBaaSDatabase, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for DatabaseCreate")
	}

	var r0 *edgecloud.DBaaSDatabase
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSDatabaseCreateRequest) (*edgecloud.DBaaSDatabase, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSDatabaseCreateRequest) *edgecloud.DBaaSDatabase); ok {
		r0 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.DBaaSDatabase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, edgecloud.DBaaSDatabaseCreateRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, edgecloud.DBaaSDatabaseCreateRequest) error); ok {
		r2 = rf(ctx, clusterID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DatabaseDelete provides a mock function with given fields: ctx, clusterID, databaseName
func (_m *DBaaSService) DatabaseDelete(ctx context.Context, clusterID string, databaseName string) (*edgecloud.DBaaSDatabase, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, databaseName)

	if len(ret) == 0 {
		panic("no return value specified for DatabaseDelete")
	}

	var r0 *edgecloud.DBaaSDatabase
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*edgecloud.DBaaSDatabase, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, databaseName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *edgecloud.DBaaSDatabase); ok {
		r0 = rf(ctx, clusterID, databaseName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.DBaaSDatabase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, databaseName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, clusterID, databaseName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DatabasesList provides a mock function with given fields: ctx, clusterID, opts
func (_m *DBaaSService) DatabasesList(ctx context.Context, clusterID string, opts *edgecloud.DBaaSDatabaseListOptions) ([]edgecloud.DBaaSDatabase, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, opts)

	if len(ret) == 0 {
		panic("no return value specified for DatabasesList")
	}

	var r0 []edgecloud.DBaaSDatabase
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.DBaaSDatabaseListOptions) ([]edgecloud.DBaaSDatabase, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.DBaaSDatabaseListOptions) []edgecloud.DBaaSDatabase); ok {
		r0 = rf(ctx, clusterID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.DBaaSDatabase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.DBaaSDatabaseListOptions) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *edgecloud.DBaaSDatabaseListOptions) error); ok {
		r2 = rf(ctx, clusterID, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DbmsList provides a mock function with given fields: ctx, opts
func (_m *DBaaSService) DbmsList(ctx context.Context, opts *edgecloud.DBaaSDbmsListOptions) ([]edgecloud.DBaaSDbms, *edgecloud.Response, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for DbmsList")
	}

	var r0 []edgecloud.DBaaSDbms
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.DBaaSDbmsListOptions) ([]edgecloud.DBaaSDbms, *edgecloud.Response, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecloud.DBaaSDbmsListOptions) []edgecloud.DBaaSDbms); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.DBaaSDbms)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecloud.DBaaSDbmsListOptions) *edgecloud.Response); ok {
		r1 = rf(ctx, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecloud.DBaaSDbmsListOptions) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserCreate provides a mock function with given fields: ctx, clusterID, reqBody
func (_m *DBaaSService) UserCreate(ctx context.Context, clusterID string, reqBody edgecloud.DBaaSUserCreateRequest) (*edgecloud.DBaaSUser, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for UserCreate")
	}

	var r0 *edgecloud.DBaaSUser
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSUserCreateRequest) (*edgecloud.DBaaSUser, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, edgecloud.DBaaSUserCreateRequest) *edgecloud.DBaaSUser); ok {
		r0 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.DBaaSUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, edgecloud.DBaaSUserCreateRequest) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, reqBody)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, edgecloud.DBaaSUserCreateRequest) error); ok {
		r2 = rf(ctx, clusterID, reqBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserDelete provides a mock function with given fields: ctx, clusterID, username
func (_m *DBaaSService) UserDelete(ctx context.Context, clusterID string, username string) (*edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, username)

	if len(ret) == 0 {
		panic("no return value specified for UserDelete")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *edgecloud.Response); ok {
		r0 = rf(ctx, clusterID, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, clusterID, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGet provides a mock function with given fields: ctx, clusterID, username
func (_m *DBaaSService) UserGet(ctx context.Context, clusterID string, username string) (*edgecloud.DBaaSUser, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, username)

	if len(ret) == 0 {
		panic("no return value specified for UserGet")
	}

	var r0 *edgecloud.DBaaSUser
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*edgecloud.DBaaSUser, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *edgecloud.DBaaSUser); ok {
		r0 = rf(ctx, clusterID, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.DBaaSUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, username)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, clusterID, username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserGrantAccess provides a mock function with given fields: ctx, clusterID, username, database
func (_m *DBaaSService) UserGrantAccess(ctx context.Context, clusterID string, username string, database string) (*edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, username, database)

	if len(ret) == 0 {
		panic("no return value specified for UserGrantAccess")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, username, database)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *edgecloud.Response); ok {
		r0 = rf(ctx, clusterID, username, database)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, clusterID, username, database)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRevokeAccess provides a mock function with given fields: ctx, clusterID, username, database
func (_m *DBaaSService) UserRevokeAccess(ctx context.Context, clusterID string, username string, database string) (*edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, username, database)

	if len(ret) == 0 {
		panic("no return value specified for UserRevokeAccess")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, username, database)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *edgecloud.Response); ok {
		r0 = rf(ctx, clusterID, username, database)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, clusterID, username, database)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUpdate provides a mock function with given fields: ctx, clusterID, username, reqBody
func (_m *DBaaSService) UserUpdate(ctx context.Context, clusterID string, username string, reqBody edgecloud.DBaaSUserUpdateRequest) (*edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, username, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for UserUpdate")
	}

	var r0 *edgecloud.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, edgecloud.DBaaSUserUpdateRequest) (*edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, username, reqBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, edgecloud.DBaaSUserUpdateRequest) *edgecloud.Response); ok {
		r0 = rf(ctx, clusterID, username, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, edgecloud.DBaaSUserUpdateRequest) error); ok {
		r1 = rf(ctx, clusterID, username, reqBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersList provides a mock function with given fields: ctx, clusterID, opts
func (_m *DBaaSService) UsersList(ctx context.Context, clusterID string, opts *edgecloud.DBaaSUserListOptions) ([]edgecloud.DBaaSUser, *edgecloud.Response, error) {
	ret := _m.Called(ctx, clusterID, opts)

	if len(ret) == 0 {
		panic("no return value specified for UsersList")
	}

	var r0 []edgecloud.DBaaSUser
	var r1 *edgecloud.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.DBaaSUserListOptions) ([]edgecloud.DBaaSUser, *edgecloud.Response, error)); ok {
		return rf(ctx, clusterID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *edgecloud.DBaaSUserListOptions) []edgecloud.DBaaSUser); ok {
		r0 = rf(ctx, clusterID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecloud.DBaaSUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *edgecloud.DBaaSUserListOptions) *edgecloud.Response); ok {
		r1 = rf(ctx, clusterID, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecloud.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *edgecloud.DBaaSUserListOptions) error); ok {
		r2 = rf(ctx, clusterID, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewDBaaSService creates a new instance of DBaaSService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBaaSService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBaaSService {
	mock := &DBaaSService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
