// Code generated by mockery v2.53.2. DO NOT EDIT.

package protectionmock

import (
	context "context"

	edgecenterprotection_go "github.com/Edge-Center/edgecenterprotection-go"
	mock "github.com/stretchr/testify/mock"
)

// OriginsService is an autogenerated mock type for the OriginsService type
type OriginsService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *OriginsService) Create(_a0 context.Context, _a1 int64, _a2 *edgecenterprotection_go.OriginCreateRequest) (*edgecenterprotection_go.Origin, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *edgecenterprotection_go.Origin
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *edgecenterprotection_go.OriginCreateRequest) (*edgecenterprotection_go.Origin, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *edgecenterprotection_go.OriginCreateRequest) *edgecenterprotection_go.Origin); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.Origin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *edgecenterprotection_go.OriginCreateRequest) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, *edgecenterprotection_go.OriginCreateRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: _a0, _a1, _a2
func (_m *OriginsService) Delete(_a0 context.Context, _a1 int64, _a2 int64) (*edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *edgecenterprotection_go.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *edgecenterprotection_go.Response); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1, _a2
func (_m *OriginsService) Get(_a0 context.Context, _a1 int64, _a2 int64) (*edgecenterprotection_go.Origin, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *edgecenterprotection_go.Origin
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*edgecenterprotection_go.Origin, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *edgecenterprotection_go.Origin); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.Origin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: _a0, _a1, _a2
func (_m *OriginsService) List(_a0 context.Context, _a1 int64, _a2 *edgecenterprotection_go.OriginListOptions) ([]edgecenterprotection_go.Origin, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []edgecenterprotection_go.Origin
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *edgecenterprotection_go.OriginListOptions) ([]edgecenterprotection_go.Origin, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *edgecenterprotection_go.OriginListOptions) []edgecenterprotection_go.Origin); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecenterprotection_go.Origin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *edgecenterprotection_go.OriginListOptions) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, *edgecenterprotection_go.OriginListOptions) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *OriginsService) Update(_a0 context.Context, _a1 int64, _a2 int64, _a3 *edgecenterprotection_go.OriginCreateRequest) (*edgecenterprotection_go.Origin, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *edgecenterprotection_go.Origin
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *edgecenterprotection_go.OriginCreateRequest) (*edgecenterprotection_go.Origin, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *edgecenterprotection_go.OriginCreateRequest) *edgecenterprotection_go.Origin); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.Origin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, *edgecenterprotection_go.OriginCreateRequest) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int64, *edgecenterprotection_go.OriginCreateRequest) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewOriginsService creates a new instance of OriginsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOriginsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OriginsService {
	mock := &OriginsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
