// Code generated by mockery v2.53.2. DO NOT EDIT.

package protectionmock

import (
	context "context"

	edgecenterprotection_go "github.com/Edge-Center/edgecenterprotection-go"
	mock "github.com/stretchr/testify/mock"
)

// ResourcesService is an autogenerated mock type for the ResourcesService type
type ResourcesService struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *ResourcesService) Create(_a0 context.Context, _a1 *edgecenterprotection_go.ResourceCreateRequest) (*edgecenterprotection_go.Resource, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *edgecenterprotection_go.Resource
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecenterprotection_go.ResourceCreateRequest) (*edgecenterprotection_go.Resource, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecenterprotection_go.ResourceCreateRequest) *edgecenterprotection_go.Resource); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecenterprotection_go.ResourceCreateRequest) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecenterprotection_go.ResourceCreateRequest) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *ResourcesService) Delete(_a0 context.Context, _a1 int64) (*edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *edgecenterprotection_go.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *edgecenterprotection_go.Response); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *ResourcesService) Get(_a0 context.Context, _a1 int64) (*edgecenterprotection_go.Resource, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *edgecenterprotection_go.Resource
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*edgecenterprotection_go.Resource, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *edgecenterprotection_go.Resource); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetDomainName provides a mock function with given fields: _a0, _a1
func (_m *ResourcesService) GetDomainName(_a0 context.Context, _a1 int64) (*edgecenterprotection_go.DnsCheck, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetDomainName")
	}

	var r0 *edgecenterprotection_go.DnsCheck
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*edgecenterprotection_go.DnsCheck, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *edgecenterprotection_go.DnsCheck); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.DnsCheck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: _a0, _a1
func (_m *ResourcesService) List(_a0 context.Context, _a1 *edgecenterprotection_go.ResourceListOptions) ([]edgecenterprotection_go.Resource, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []edgecenterprotection_go.Resource
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *edgecenterprotection_go.ResourceListOptions) ([]edgecenterprotection_go.Resource, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *edgecenterprotection_go.ResourceListOptions) []edgecenterprotection_go.Resource); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]edgecenterprotection_go.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *edgecenterprotection_go.ResourceListOptions) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *edgecenterprotection_go.ResourceListOptions) error); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *ResourcesService) Update(_a0 context.Context, _a1 int64, _a2 *edgecenterprotection_go.ResourceUpdateRequest) (*edgecenterprotection_go.Resource, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *edgecenterprotection_go.Resource
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *edgecenterprotection_go.ResourceUpdateRequest) (*edgecenterprotection_go.Resource, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *edgecenterprotection_go.ResourceUpdateRequest) *edgecenterprotection_go.Resource); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *edgecenterprotection_go.ResourceUpdateRequest) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, *edgecenterprotection_go.ResourceUpdateRequest) error); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ValidateResourceCreate provides a mock function with given fields: _a0
func (_m *ResourcesService) ValidateResourceCreate(_a0 edgecenterprotection_go.ResourceCreateRequest) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ValidateResourceCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(edgecenterprotection_go.ResourceCreateRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateResourceUpdate provides a mock function with given fields: _a0
func (_m *ResourcesService) ValidateResourceUpdate(_a0 edgecenterprotection_go.ResourceUpdateRequest) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ValidateResourceUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(edgecenterprotection_go.ResourceUpdateRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewResourcesService creates a new instance of ResourcesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourcesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourcesService {
	mock := &ResourcesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
