// Code generated by mockery v2.53.2. DO NOT EDIT.

package protectionmock

import (
	context "context"

	edgecenterprotection_go "github.com/Edge-Center/edgecenterprotection-go"
	mock "github.com/stretchr/testify/mock"
)

// ServicesService is an autogenerated mock type for the ServicesService type
type ServicesService struct {
	mock.Mock
}

// GetInfrastructureProtectionService provides a mock function with given fields: _a0
func (_m *ServicesService) GetInfrastructureProtectionService(_a0 context.Context) (*edgecenterprotection_go.InfrastructureProtectionDetails, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetInfrastructureProtectionService")
	}

	var r0 *edgecenterprotection_go.InfrastructureProtectionDetails
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (*edgecenterprotection_go.InfrastructureProtectionDetails, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *edgecenterprotection_go.InfrastructureProtectionDetails); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.InfrastructureProtectionDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetWebProtectionService provides a mock function with given fields: _a0
func (_m *ServicesService) GetWebProtectionService(_a0 context.Context) (*edgecenterprotection_go.WebProtectionDetails, *edgecenterprotection_go.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetWebProtectionService")
	}

	var r0 *edgecenterprotection_go.WebProtectionDetails
	var r1 *edgecenterprotection_go.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (*edgecenterprotection_go.WebProtectionDetails, *edgecenterprotection_go.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *edgecenterprotection_go.WebProtectionDetails); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*edgecenterprotection_go.WebProtectionDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) *edgecenterprotection_go.Response); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*edgecenterprotection_go.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewServicesService creates a new instance of ServicesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServicesService {
	mock := &ServicesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
