# Generated by v2migrate (terraform-provider-edgecenter).
# Review the blocks, then run:
#   terraform plan -out=v2-migrate.tfplan
#   terraform apply v2-migrate.tfplan
# The plan must only import and forget resources, no destroy and no create.
# After a successful apply delete this file, terraform plan must then show no changes.
# Requires terraform >= 1.7.

removed {
  from = edgecenter_loadbalancer.lb
  lifecycle {
    destroy = false
  }
}

import {
  to = edgecenter_loadbalancerv2.lb
  id = "1:2:5f8a3c1d-9a4b-4c2e-8f6d-7e5a4b3c2d1e"
}

import {
  to = edgecenter_lblistener.lb
  id = "1:2:a336f28c-fbb0-4256-9545-e905bed9f48f:5f8a3c1d-9a4b-4c2e-8f6d-7e5a4b3c2d1e"
}

removed {
  from = edgecenter_instance.web
  lifecycle {
    destroy = false
  }
}

import {
  to = edgecenter_instanceV2.web
  id = "1:2:447d2959-8ae0-4ca0-8d47-9f050a3637d7"
}

removed {
  from = edgecenter_reseller_images.rimgs
  lifecycle {
    destroy = false
  }
}

import {
  to = edgecenter_reseller_imagesV2.rimgs
  id = "reseller:123456"
}
