// Code generated by mockery v2.53.2. DO NOT EDIT.

package cdnmock

import (
	context "context"

	lecerts "github.com/Edge-Center/edgecentercdn-go/lecerts"
	mock "github.com/stretchr/testify/mock"
)

// LECertService is an autogenerated mock type for the LECertService type
type LECertService struct {
	mock.Mock
}

// CancelLECert provides a mock function with given fields: ctx, resourceID, active
func (_m *LECertService) CancelLECert(ctx context.Context, resourceID int64, active bool) error {
	ret := _m.Called(ctx, resourceID, active)

	if len(ret) == 0 {
		panic("no return value specified for CancelLECert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) error); ok {
		r0 = rf(ctx, resourceID, active)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateLECert provides a mock function with given fields: ctx, resourceID
func (_m *LECertService) CreateLECert(ctx context.Context, resourceID int64) error {
	ret := _m.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for CreateLECert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, resourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLECert provides a mock function with given fields: ctx, resourceID, force
func (_m *LECertService) DeleteLECert(ctx context.Context, resourceID int64, force bool) error {
	ret := _m.Called(ctx, resourceID, force)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLECert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) error); ok {
		r0 = rf(ctx, resourceID, force)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLECert provides a mock function with given fields: ctx, resourceID
func (_m *LECertService) GetLECert(ctx context.Context, resourceID int64) (*lecerts.LECertStatus, error) {
	ret := _m.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for GetLECert")
	}

	var r0 *lecerts.LECertStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*lecerts.LECertStatus, error)); ok {
		return rf(ctx, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *lecerts.LECertStatus); ok {
		r0 = rf(ctx, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lecerts.LECertStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IssueLECert provides a mock function with given fields: ctx, resourceID, req
func (_m *LECertService) IssueLECert(ctx context.Context, resourceID int64, req *lecerts.IssueRequest) error {
	ret := _m.Called(ctx, resourceID, req)

	if len(ret) == 0 {
		panic("no return value specified for IssueLECert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *lecerts.IssueRequest) error); ok {
		r0 = rf(ctx, resourceID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLECert provides a mock function with given fields: ctx, resourceID
func (_m *LECertService) UpdateLECert(ctx context.Context, resourceID int64) error {
	ret := _m.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLECert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, resourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLECertService creates a new instance of LECertService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLECertService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LECertService {
	mock := &LECertService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
