// Code generated by mockery v2.53.2. DO NOT EDIT.

package cdnmock

import (
	context "context"

	origingroups "github.com/Edge-Center/edgecentercdn-go/origingroups"
	mock "github.com/stretchr/testify/mock"
)

// OriginGroupService is an autogenerated mock type for the OriginGroupService type
type OriginGroupService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *OriginGroupService) Create(ctx context.Context, req *origingroups.GroupRequest) (*origingroups.OriginGroup, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *origingroups.OriginGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *origingroups.GroupRequest) (*origingroups.OriginGroup, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *origingroups.GroupRequest) *origingroups.OriginGroup); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*origingroups.OriginGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *origingroups.GroupRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *OriginGroupService) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *OriginGroupService) Get(ctx context.Context, id int64) (*origingroups.OriginGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *origingroups.OriginGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*origingroups.OriginGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *origingroups.OriginGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*origingroups.OriginGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *OriginGroupService) Update(ctx context.Context, id int64, req *origingroups.GroupRequest) (*origingroups.OriginGroup, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *origingroups.OriginGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *origingroups.GroupRequest) (*origingroups.OriginGroup, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *origingroups.GroupRequest) *origingroups.OriginGroup); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*origingroups.OriginGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *origingroups.GroupRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOriginGroupService creates a new instance of OriginGroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOriginGroupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OriginGroupService {
	mock := &OriginGroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
