// Code generated by mockery v2.53.2. DO NOT EDIT.

package cdnmock

import (
	context "context"

	tools "github.com/Edge-Center/edgecentercdn-go/tools"
	mock "github.com/stretchr/testify/mock"
)

// ResourceToolsService is an autogenerated mock type for the ResourceToolsService type
type ResourceToolsService struct {
	mock.Mock
}

// ClientInfo provides a mock function with given fields: ctx
func (_m *ResourceToolsService) ClientInfo(ctx context.Context) (*tools.ClientInfoResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClientInfo")
	}

	var r0 *tools.ClientInfoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*tools.ClientInfoResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *tools.ClientInfoResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tools.ClientInfoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Purge provides a mock function with given fields: ctx, id, req
func (_m *ResourceToolsService) Purge(ctx context.Context, id int64, req *tools.PurgeRequest) (*tools.PurgeResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Purge")
	}

	var r0 *tools.PurgeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *tools.PurgeRequest) (*tools.PurgeResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *tools.PurgeRequest) *tools.PurgeResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tools.PurgeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *tools.PurgeRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Whoami provides a mock function with given fields: ctx
func (_m *ResourceToolsService) Whoami(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Whoami")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResourceToolsService creates a new instance of ResourceToolsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceToolsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceToolsService {
	mock := &ResourceToolsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
