// Code generated by mockery v2.53.2. DO NOT EDIT.

package cdnmock

import (
	context "context"

	statistics "github.com/Edge-Center/edgecentercdn-go/statistics"
	mock "github.com/stretchr/testify/mock"
)

// ResourceStatisticsService is an autogenerated mock type for the ResourceStatisticsService type
type ResourceStatisticsService struct {
	mock.Mock
}

// GetTableData provides a mock function with given fields: ctx, req
func (_m *ResourceStatisticsService) GetTableData(ctx context.Context, req *statistics.ResourceStatisticsTableRequest) (*[]statistics.ResourceStatisticsTableData, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTableData")
	}

	var r0 *[]statistics.ResourceStatisticsTableData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *statistics.ResourceStatisticsTableRequest) (*[]statistics.ResourceStatisticsTableData, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *statistics.ResourceStatisticsTableRequest) *[]statistics.ResourceStatisticsTableData); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]statistics.ResourceStatisticsTableData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *statistics.ResourceStatisticsTableRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTimeSeriesData provides a mock function with given fields: ctx, req
func (_m *ResourceStatisticsService) GetTimeSeriesData(ctx context.Context, req *statistics.ResourceStatisticsTimeSeriesRequest) (*[]statistics.ResourceStatisticsTimeSeriesData, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeSeriesData")
	}

	var r0 *[]statistics.ResourceStatisticsTimeSeriesData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *statistics.ResourceStatisticsTimeSeriesRequest) (*[]statistics.ResourceStatisticsTimeSeriesData, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *statistics.ResourceStatisticsTimeSeriesRequest) *[]statistics.ResourceStatisticsTimeSeriesData); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]statistics.ResourceStatisticsTimeSeriesData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *statistics.ResourceStatisticsTimeSeriesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResourceStatisticsService creates a new instance of ResourceStatisticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceStatisticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceStatisticsService {
	mock := &ResourceStatisticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
