// Code generated by mockery v2.53.2. DO NOT EDIT.

package cdnmock

import (
	context "context"

	resources "github.com/Edge-Center/edgecentercdn-go/resources"
	mock "github.com/stretchr/testify/mock"
)

// ResourceService is an autogenerated mock type for the ResourceService type
type ResourceService struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, filter
func (_m *ResourceService) Count(ctx context.Context, filter *resources.ListFilterRequest) (uint, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *resources.ListFilterRequest) (uint, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *resources.ListFilterRequest) uint); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *resources.ListFilterRequest) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, req
func (_m *ResourceService) Create(ctx context.Context, req *resources.CreateRequest) (*resources.Resource, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *resources.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *resources.CreateRequest) (*resources.Resource, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *resources.CreateRequest) *resources.Resource); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *resources.CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, resourceID
func (_m *ResourceService) Delete(ctx context.Context, resourceID int64) error {
	ret := _m.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, resourceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *ResourceService) Get(ctx context.Context, id int64) (*resources.Resource, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *resources.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*resources.Resource, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *resources.Resource); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *ResourceService) List(ctx context.Context, filter *resources.ListFilterRequest) ([]resources.Resource, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []resources.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *resources.ListFilterRequest) ([]resources.Resource, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *resources.ListFilterRequest) []resources.Resource); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resources.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *resources.ListFilterRequest) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Page provides a mock function with given fields: ctx, offset, size, filter
func (_m *ResourceService) Page(ctx context.Context, offset uint, size uint, filter *resources.ListFilterRequest) (*resources.PaginatedResource, error) {
	ret := _m.Called(ctx, offset, size, filter)

	if len(ret) == 0 {
		panic("no return value specified for Page")
	}

	var r0 *resources.PaginatedResource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *resources.ListFilterRequest) (*resources.PaginatedResource, error)); ok {
		return rf(ctx, offset, size, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *resources.ListFilterRequest) *resources.PaginatedResource); ok {
		r0 = rf(ctx, offset, size, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.PaginatedResource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *resources.ListFilterRequest) error); ok {
		r1 = rf(ctx, offset, size, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *ResourceService) Update(ctx context.Context, id int64, req *resources.UpdateRequest) (*resources.Resource, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *resources.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *resources.UpdateRequest) (*resources.Resource, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *resources.UpdateRequest) *resources.Resource); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resources.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *resources.UpdateRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResourceService creates a new instance of ResourceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceService {
	mock := &ResourceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
