// Code generated by mockery v2.53.2. DO NOT EDIT.

package cdnmock

import (
	context "context"

	rules "github.com/Edge-Center/edgecentercdn-go/rules"
	mock "github.com/stretchr/testify/mock"
)

// RulesService is an autogenerated mock type for the RulesService type
type RulesService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, resourceID, req
func (_m *RulesService) Create(ctx context.Context, resourceID int64, req *rules.CreateRequest) (*rules.Rule, error) {
	ret := _m.Called(ctx, resourceID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *rules.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *rules.CreateRequest) (*rules.Rule, error)); ok {
		return rf(ctx, resourceID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *rules.CreateRequest) *rules.Rule); ok {
		r0 = rf(ctx, resourceID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rules.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *rules.CreateRequest) error); ok {
		r1 = rf(ctx, resourceID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, resourceID, ruleID
func (_m *RulesService) Delete(ctx context.Context, resourceID int64, ruleID int64) error {
	ret := _m.Called(ctx, resourceID, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, resourceID, ruleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, resourceID, ruleID
func (_m *RulesService) Get(ctx context.Context, resourceID int64, ruleID int64) (*rules.Rule, error) {
	ret := _m.Called(ctx, resourceID, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rules.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*rules.Rule, error)); ok {
		return rf(ctx, resourceID, ruleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *rules.Rule); ok {
		r0 = rf(ctx, resourceID, ruleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rules.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, resourceID, ruleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, resourceID, ruleID, req
func (_m *RulesService) Update(ctx context.Context, resourceID int64, ruleID int64, req *rules.UpdateRequest) (*rules.Rule, error) {
	ret := _m.Called(ctx, resourceID, ruleID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *rules.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *rules.UpdateRequest) (*rules.Rule, error)); ok {
		return rf(ctx, resourceID, ruleID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *rules.UpdateRequest) *rules.Rule); ok {
		r0 = rf(ctx, resourceID, ruleID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rules.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, *rules.UpdateRequest) error); ok {
		r1 = rf(ctx, resourceID, ruleID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRulesService creates a new instance of RulesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRulesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RulesService {
	mock := &RulesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
