// Code generated by mockery v2.53.2. DO NOT EDIT.

package cdnmock

import (
	context "context"

	shielding "github.com/Edge-Center/edgecentercdn-go/shielding"
	mock "github.com/stretchr/testify/mock"
)

// ShieldingService is an autogenerated mock type for the ShieldingService type
type ShieldingService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, resourceID
func (_m *ShieldingService) Get(ctx context.Context, resourceID int64) (*shielding.ShieldingData, error) {
	ret := _m.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *shielding.ShieldingData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*shielding.ShieldingData, error)); ok {
		return rf(ctx, resourceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *shielding.ShieldingData); ok {
		r0 = rf(ctx, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shielding.ShieldingData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShieldingLocations provides a mock function with given fields: ctx
func (_m *ShieldingService) GetShieldingLocations(ctx context.Context) (*[]shielding.ShieldingLocations, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetShieldingLocations")
	}

	var r0 *[]shielding.ShieldingLocations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]shielding.ShieldingLocations, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]shielding.ShieldingLocations); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]shielding.ShieldingLocations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, resourceID, req
func (_m *ShieldingService) Update(ctx context.Context, resourceID int64, req *shielding.UpdateShieldingData) (*shielding.ShieldingData, error) {
	ret := _m.Called(ctx, resourceID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *shielding.ShieldingData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *shielding.UpdateShieldingData) (*shielding.ShieldingData, error)); ok {
		return rf(ctx, resourceID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *shielding.UpdateShieldingData) *shielding.ShieldingData); ok {
		r0 = rf(ctx, resourceID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shielding.ShieldingData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *shielding.UpdateShieldingData) error); ok {
		r1 = rf(ctx, resourceID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShieldingService creates a new instance of ShieldingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShieldingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShieldingService {
	mock := &ShieldingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
