// Code generated by mockery v2.53.2. DO NOT EDIT.

package cdnmock

import (
	context "context"

	sslcerts "github.com/Edge-Center/edgecentercdn-go/sslcerts"
	mock "github.com/stretchr/testify/mock"
)

// SSLCertService is an autogenerated mock type for the SSLCertService type
type SSLCertService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *SSLCertService) Create(ctx context.Context, req *sslcerts.CreateRequest) (*sslcerts.Cert, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *sslcerts.Cert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sslcerts.CreateRequest) (*sslcerts.Cert, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sslcerts.CreateRequest) *sslcerts.Cert); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sslcerts.Cert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sslcerts.CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SSLCertService) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *SSLCertService) Get(ctx context.Context, id int64) (*sslcerts.Cert, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sslcerts.Cert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*sslcerts.Cert, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *sslcerts.Cert); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sslcerts.Cert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSSLCertService creates a new instance of SSLCertService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSSLCertService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SSLCertService {
	mock := &SSLCertService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
