// Code generated by mockery v2.53.2. DO NOT EDIT.

package storagemock

import (
	buckets "github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/client/buckets"

	models "github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/models"
	mock "github.com/stretchr/testify/mock"
)

// StorageBucketService is an autogenerated mock type for the StorageBucketService type
type StorageBucketService struct {
	mock.Mock
}

// BucketsList provides a mock function with given fields: opts
func (_m *StorageBucketService) BucketsList(opts ...func(*buckets.StorageListBucketsHTTPParams)) ([]models.BucketDto, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BucketsList")
	}

	var r0 []models.BucketDto
	var r1 error
	if rf, ok := ret.Get(0).(func(...func(*buckets.StorageListBucketsHTTPParams)) ([]models.BucketDto, error)); ok {
		return rf(opts...)
	}
	if rf, ok := ret.Get(0).(func(...func(*buckets.StorageListBucketsHTTPParams)) []models.BucketDto); ok {
		r0 = rf(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.BucketDto)
		}
	}

	if rf, ok := ret.Get(1).(func(...func(*buckets.StorageListBucketsHTTPParams)) error); ok {
		r1 = rf(opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBucket provides a mock function with given fields: opts
func (_m *StorageBucketService) CreateBucket(opts ...func(*buckets.StorageBucketCreateHTTPParams)) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...func(*buckets.StorageBucketCreateHTTPParams)) error); ok {
		r0 = rf(opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBucket provides a mock function with given fields: opts
func (_m *StorageBucketService) DeleteBucket(opts ...func(*buckets.StorageBucketRemoveHTTPParams)) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBucket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...func(*buckets.StorageBucketRemoveHTTPParams)) error); ok {
		r0 = rf(opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorageBucketService creates a new instance of StorageBucketService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageBucketService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageBucketService {
	mock := &StorageBucketService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
