// Code generated by mockery v2.53.2. DO NOT EDIT.

package storagemock

import (
	locations "github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/client/locations"
	models "github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/models"
	mock "github.com/stretchr/testify/mock"
)

// StorageLocationService is an autogenerated mock type for the StorageLocationService type
type StorageLocationService struct {
	mock.Mock
}

// LocationsList provides a mock function with given fields: opts
func (_m *StorageLocationService) LocationsList(opts ...func(*locations.LocationListHTTPParams)) ([]models.ClientLocationRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LocationsList")
	}

	var r0 []models.ClientLocationRes
	var r1 error
	if rf, ok := ret.Get(0).(func(...func(*locations.LocationListHTTPParams)) ([]models.ClientLocationRes, error)); ok {
		return rf(opts...)
	}
	if rf, ok := ret.Get(0).(func(...func(*locations.LocationListHTTPParams)) []models.ClientLocationRes); ok {
		r0 = rf(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ClientLocationRes)
		}
	}

	if rf, ok := ret.Get(1).(func(...func(*locations.LocationListHTTPParams)) error); ok {
		r1 = rf(opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorageLocationService creates a new instance of StorageLocationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageLocationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageLocationService {
	mock := &StorageLocationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
