// Code generated by mockery v2.53.2. DO NOT EDIT.

package storagemock

import (
	storages "github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/client/storages"
	models "github.com/Edge-Center/edgecenter-storage-sdk-go/swagger/models"
	mock "github.com/stretchr/testify/mock"
)

// StorageS3Service is an autogenerated mock type for the StorageS3Service type
type StorageS3Service struct {
	mock.Mock
}

// CreateStorage provides a mock function with given fields: opts
func (_m *StorageS3Service) CreateStorage(opts ...func(*storages.StorageCreateHTTPParams)) (*models.Storage, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateStorage")
	}

	var r0 *models.Storage
	var r1 error
	if rf, ok := ret.Get(0).(func(...func(*storages.StorageCreateHTTPParams)) (*models.Storage, error)); ok {
		return rf(opts...)
	}
	if rf, ok := ret.Get(0).(func(...func(*storages.StorageCreateHTTPParams)) *models.Storage); ok {
		r0 = rf(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Storage)
		}
	}

	if rf, ok := ret.Get(1).(func(...func(*storages.StorageCreateHTTPParams)) error); ok {
		r1 = rf(opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteStorage provides a mock function with given fields: opts
func (_m *StorageS3Service) DeleteStorage(opts ...func(*storages.StorageDeleteHTTPParams)) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStorage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...func(*storages.StorageDeleteHTTPParams)) error); ok {
		r0 = rf(opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoragesList provides a mock function with given fields: opts
func (_m *StorageS3Service) StoragesList(opts ...func(*storages.StorageListHTTPV2Params)) ([]models.Storage, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StoragesList")
	}

	var r0 []models.Storage
	var r1 error
	if rf, ok := ret.Get(0).(func(...func(*storages.StorageListHTTPV2Params)) ([]models.Storage, error)); ok {
		return rf(opts...)
	}
	if rf, ok := ret.Get(0).(func(...func(*storages.StorageListHTTPV2Params)) []models.Storage); ok {
		r0 = rf(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Storage)
		}
	}

	if rf, ok := ret.Get(1).(func(...func(*storages.StorageListHTTPV2Params)) error); ok {
		r1 = rf(opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorageS3Service creates a new instance of StorageS3Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageS3Service(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageS3Service {
	mock := &StorageS3Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
